version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify the Node.js version (adjust as needed)
    commands:
      - echo Installing dependencies...
      - npm install  # Installs dependencies based on package.json

  pre_build:
    commands:
      - echo Running tests...
      - npm test  # Runs the Jest tests defined in your test scripts

  build:
    commands:
      - echo Build started on `date`
      # If using a build process (e.g., npm run build), include it here
      # For example, if you have a build command:
      # - npm run build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'  # Include all files for deployment
  base-directory: .  # Adjust this to the directory containing your deployment files
