version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specify Node.js version 18 to support Puppeteer and modern syntax
    commands:
      - echo Installing dependencies...
      - npm install  # Installs dependencies based on package.json
      - echo Installing libraries needed for Puppeteer...
      - yum install -y libgbm libXcomposite libXcursor libXdamage libXi libXtst cups-libs dbus-glib libXrandr libXrandr libxshmfence mesa-libgbm alsa-lib atk at-spi2-atk gtk3

  pre_build:
    commands:
      - echo Running tests...
      - npm test  # Runs the Jest tests defined in your test scripts

  build:
    commands:
      - echo Build started on `date`
      # If using a build process (e.g., npm run build), include it here

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'  # Include all files for deployment
  base-directory: .  # Adjust this to the directory containing your deployment files
