version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify the Node.js version (adjust as needed)
    commands:
      - echo Installing dependencies...
      - npm install  # Installs dependencies based on package.json
  build:
    commands:
      - echo Build started on `date`
      # If using a build process (e.g., npm run build), include it here
      # - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: .  # Ensure this points to the directory where your server files are located
